### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by YoushaaMurhij** [MIT-SPARK/PACE#1]
Thanks for sharing this great work!
I wonder if you have a plan to release the code in the near future? 

Thanks

**Comment by jingnanshi** [comment]
@YoushaaMurhij thank you for your interest! If you email me (see my github profile) I'll send you a copy of the code (not cleaned up, but suitable for use in your research if you are willing to adapt it a bit).

**Comment by ZhihangCui** [comment]
Same question，May I trouble you to share the code with me via email?

**Comment by cz19860416** [comment]
> @YoushaaMurhij thank you for your interest! If you email me (see my github profile) I'll send you a copy of the code (not cleaned up, but suitable for use in your research if you are willing to adapt it a bit).

Dear author, I have sent you a request email for the code, but no reply. 
Could you update the code just in this repo as you said. Thank you !

**Comment by jingnanshi** [comment]
@cz19860416 Sorry for the delay, I have uploaded the solvers to this repo. Please let me know if you have additional questions (the code is a bit messy).

**Comment by jingnanshi** [comment]
@ZhihangCui Sorry for the delay, I have uploaded the solvers to this repo. Please let me know if you have additional questions (the code is a bit messy).
